version: '3'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - '9090:9090'
    volumes: 
      - '${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml'
      - prometheus-data:/etc/prometheus

  grafana:
    links:
      - prometheus
    image: grafana/grafana
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - '3000:3000'

volumes:
  grafana-data:
    driver: local
  prometheus-data:
    driver: local
