{
 "title": "Dynamics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Log Events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(logback_events_total[60s])",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Saga Instance Created",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(saga_instance_started_total[30s])",
     "legendFormat": "{{saga_name}}"
    }
   ]
  },
  {
   "title": "HTTP Anomalies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{status!~\"200\"}[60s])",
     "legendFormat": "{{status}} {{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Active Saga Instances",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "saga_instance_started_total - saga_instance_compensated_total",
     "legendFormat": "{{saga_name}}"
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(exception) (rate(http_server_requests_seconds_count{exception!~\"None\"}[1m]))",
     "legendFormat": "HTTP {{exception}}"
    },
    {
     "expr": "rate(coordinator_exception_thrown_total[1m])",
     "legendFormat": "{{exception}}"
    }
   ]
  },
  {
   "title": "Average time by steps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "saga_template_step_executed_sum / saga_template_step_executed_count",
     "legendFormat": "{{saga_name}}:{{step_name}}"
    }
   ]
  }
 ]
}